name: DangerJS

on:
  pull_request_target:

jobs:
  danger:
    runs-on: ubuntu-latest
    #if: github.event_name  == 'pull_request' # only run pull requests, no really
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0

    - uses: danger/danger-js@9.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DANGER_DISABLE_TRANSPILATION: "true"